language: android
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - libfile-mimeinfo-perl
branches:
  except:
    - l10n_alpha2
    - alpha
env:
  - MAJOR_MINOR=1.2.0 UPSTREAM_BRANCH=beta
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
before_install:
  - 'yes | sdkmanager "platforms;android-27"'
  - 'chmod a+x ./scripts/deploy-*.sh'
  - 'chmod a+x ./scripts/changelog.sh'
  - 'chmod a+x ./scripts/s3-upload.sh'
  - 'git fetch --tags'
before_script:
  - 'bash scripts/changelog.sh > changelog.txt'
  # added
  - git remote add upstream https://github.com/LawnchairLauncher/Lawnchair
  - git fetch upstream $UPSTREAM_BRANCH
  - git merge $UPSTREAM_BRANCH
  - rm -f app/debug.jks
  - keytool -genkey -v -keystore app/debug.jks -storepass $STORE_PASSWORD -alias Lawnchair -keypass $KEY_PASSWORD -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
script:
  - 'bash ./gradlew assembleDebug check;'
  - 'bash ./gradlew app:assembleRelease check;'
before_cache:
  - 'rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock'
  - 'rm -fr $HOME/.gradle/caches/*/plugin-resolution/'
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_deploy:
  - "cp app/build/outputs/apk/debug/app-debug.apk Lawnchair-$TRAVIS_BRANCH-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.apk"
  - "cp app/build/outputs/mapping/debug/mapping.txt proguard-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.txt"
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-s3.sh
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH_TOKEN
    #added:
    file: "Lawnchair-$TRAVIS_BRANCH-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.apk"
    #file: "Lawnchair-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.apk"
    on:
      #added:
      all_branches: true
      #old: tags: true
